### ISSUE TITLE
Como integrar  gr-mer    en  bogdanDIA/DVB-T ?

### ISSUE THREAD

**Issue by xugmu** [git-artes/gr-mer#1]
Fantástico vuestro trabajo ,gracias a  vuestro módulo de  adquisición de  símbolos   mi MSI.SDR engancha a la primera  y se muestra estable  incluso con  señales  con poca calidad.

Estaria bien poder utilizar  el modulo que habéis  creado para  poder medir el MER  en números  ,Entre otras cosas porque  la constelación  difiere la de un medidor  "real". Da la impresión de que es  mas lineal que logarítmica   o algo así 
 .

Saludos y gracias por vuestro trabajo

**Comment by xugmu** [comment]
Me contesto a mi mismo ,es realmente sencillo, solo hay  que conectar  demod reference signals   con  hw impairments 

De nuevo gracias por vuestro fantástico trabajo

**Comment by git-artes** [comment]
impecable, me alegro.
cierro esto.
saludos
